# docker-compose.yml for Fall 2025

services:
  owncloud:
    image: stevehendrikse/malwarelabowncloud:6.0
    ports:
      - 80:80
    expose:
      - 80
    environment:
      EXTERNAL_IP: ${EXT_IP}
      EXTRA_IP: 172.16.10.132
    volumes:
      - '${HOME}/secu74000:/mnt/data/files:cached'
  
  jupyter:
    image: stevehendrikse/malwarelabjupyter:7.0
    ports:
      - 8000:8888
    expose:
      - 8000
    links:
      - owncloud
    environment:
      USE_OWNCLOUD: YES
      OC_USER: "admin"
      OC_PASS: "p@ssw0rd"

# comment these lines if you do not wish to run a
# text editor on port 8001
  codeserver:
    image: stevehendrikse/malwarelabcodeserver:7.0
    ports:
      - 8001:8001
    expose:
      - 8001
    links:
      - owncloud
    environment:
      USE_OWNCLOUD: YES
      OC_USER: "admin"
      OC_PASS: "p@ssw0rd"


